#!/bin/bash
file_name='*\\'"Best School"'\\*$?*****:)'
content="Best School"
echo -n "$content" > "$file_name"
echo >> "$file_name"
echo "File '$file_name' has been created with the content '$content' followed by a newline."
